export default {
  GET_DEVICE_TYPES: 'GET_DEVICE_TYPES',
  SET_DEVICE_TYPES: 'SET_DEVICE_TYPES',
  MUTATE_DEVICE_TYPES: 'MUTATE_DEVICE_TYPES',
  GET_IS_AD_BLOCK: 'GET_IS_AD_BLOCK',
  SET_IS_AD_BLOCK: 'SET_IS_AD_BLOCK',
  MUTATE_IS_AD_BLOCK: 'MUTATE_IS_AD_BLOCK',
  GET_BROWSER_NAME: 'GET_BROWSER_NAME',
  SET_BROWSER_NAME: 'SET_BROWSER_NAME',
  MUTATE_BROWSER_NAME: 'MUTATE_BROWSER_NAME',
};
